server:
  port: 8081
  servlet:
    session:
      timeout: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    cache: false
#  mvc:
#    static-path-pattern: /**
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
